export type FullTransaction = {
  id: string
  userId: string
  merchant: string
  transactionId: string
  amount: number
  date: string
  logo: string
  category: string
  status: "completed" | "pending" | "failed"
  type: "expense" | "income"
  notes?: string
  merchantInfo?: string
  cardLast4?: string
}
export const logo = (domain: string) =>
  `/logos/${domain.replace(/\./g, "-")}.png`

export const fullTransactions: FullTransaction[] = [
  {
    id: "t1",
    userId: "1",
    merchant: "Spotify",
    transactionId: "INV_920076",
    amount: -9.99,
    date: "Apr 10, 2026",
    logo: logo("spotify.com"),
    category: "Entertainment",
    status: "completed",
    type: "expense",
    merchantInfo: "Spotify AB, Stockholm, SE",
    cardLast4: "4589",
  },
  {
    id: "t2",
    userId: "1",
    merchant: "AWS Cloud Services",
    transactionId: "INV_918263",
    amount: -120.0,
    date: "Apr 09, 2026",
    logo: "/logos/aws-amazon-com.svg",
    category: "Technology",
    status: "completed",
    type: "expense",
    merchantInfo: "Amazon Web Services, Seattle, WA",
    cardLast4: "4589",
  },
  {
    id: "t3",
    userId: "1",
    merchant: "Stripe Payout",
    transactionId: "TXN_847291",
    amount: 4250.0,
    date: "Apr 08, 2026",
    logo: logo("stripe.com"),
    category: "Income",
    status: "completed",
    type: "income",
    merchantInfo: "Stripe Inc, San Francisco, CA",
  },
  {
    id: "t4",
    userId: "1",
    merchant: "Figma Pro",
    transactionId: "INV_773920",
    amount: -15.0,
    date: "Apr 07, 2026",
    logo: logo("figma.com"),
    category: "Design",
    status: "completed",
    type: "expense",
    merchantInfo: "Figma Inc, San Francisco, CA",
    cardLast4: "7321",
  },
  {
    id: "t5",
    userId: "1",
    merchant: "ChatGPT Plus",
    transactionId: "INV_920077",
    amount: -20.0,
    date: "Apr 06, 2026",
    logo: logo("openai.com"),
    category: "AI Tools",
    status: "completed",
    type: "expense",
    merchantInfo: "OpenAI LLC, San Francisco, CA",
    cardLast4: "4589",
  },
  {
    id: "t6",
    userId: "1",
    merchant: "Google Workspace",
    transactionId: "INV_661204",
    amount: -12.0,
    date: "Apr 05, 2026",
    logo: logo("google.com"),
    category: "Productivity",
    status: "completed",
    type: "expense",
    merchantInfo: "Google LLC, Mountain View, CA",
    cardLast4: "4589",
  },
  {
    id: "t7",
    userId: "1",
    merchant: "Client Payment",
    transactionId: "TXN_559831",
    amount: 8500.0,
    date: "Apr 04, 2026",
    logo: logo("paypal.com"),
    category: "Income",
    status: "completed",
    type: "income",
    merchantInfo: "PayPal Holdings, San Jose, CA",
  },
  {
    id: "t8",
    userId: "1",
    merchant: "Uber",
    transactionId: "INV_882341",
    amount: -24.5,
    date: "Apr 03, 2026",
    logo: logo("uber.com"),
    category: "Transport",
    status: "completed",
    type: "expense",
    merchantInfo: "Uber Technologies, San Francisco, CA",
    cardLast4: "9012",
  },
  {
    id: "t9",
    userId: "1",
    merchant: "Netflix",
    transactionId: "INV_773001",
    amount: -15.99,
    date: "Apr 02, 2026",
    logo: logo("netflix.com"),
    category: "Entertainment",
    status: "completed",
    type: "expense",
    merchantInfo: "Netflix Inc, Los Gatos, CA",
    cardLast4: "4589",
  },
  {
    id: "t10",
    userId: "1",
    merchant: "Amazon",
    transactionId: "INV_990123",
    amount: -89.99,
    date: "Apr 01, 2026",
    logo: logo("amazon.com"),
    category: "Shopping",
    status: "completed",
    type: "expense",
    merchantInfo: "Amazon.com Inc, Seattle, WA",
    cardLast4: "4589",
  },
  {
    id: "t11",
    userId: "1",
    merchant: "Starbucks",
    transactionId: "INV_445501",
    amount: -6.75,
    date: "Mar 31, 2026",
    logo: logo("starbucks.com"),
    category: "Food & Dining",
    status: "completed",
    type: "expense",
    cardLast4: "9012",
  },
  {
    id: "t12",
    userId: "1",
    merchant: "DoorDash",
    transactionId: "INV_334112",
    amount: -32.4,
    date: "Mar 30, 2026",
    logo: logo("doordash.com"),
    category: "Food & Dining",
    status: "completed",
    type: "expense",
    cardLast4: "4589",
  },
  {
    id: "t13",
    userId: "1",
    merchant: "Adobe Creative Cloud",
    transactionId: "INV_221098",
    amount: -54.99,
    date: "Mar 29, 2026",
    logo: logo("adobe.com"),
    category: "Design",
    status: "completed",
    type: "expense",
    merchantInfo: "Adobe Inc, San Jose, CA",
    cardLast4: "7321",
  },
  {
    id: "t14",
    userId: "1",
    merchant: "Slack",
    transactionId: "INV_110987",
    amount: -8.75,
    date: "Mar 28, 2026",
    logo: logo("slack.com"),
    category: "Productivity",
    status: "completed",
    type: "expense",
    cardLast4: "4589",
  },
  {
    id: "t15",
    userId: "1",
    merchant: "GitHub Pro",
    transactionId: "INV_998877",
    amount: -4.0,
    date: "Mar 27, 2026",
    logo: logo("github.com"),
    category: "Technology",
    status: "completed",
    type: "expense",
    merchantInfo: "GitHub Inc, San Francisco, CA",
    cardLast4: "4589",
  },
  {
    id: "t16",
    userId: "1",
    merchant: "Notion",
    transactionId: "INV_887766",
    amount: -10.0,
    date: "Mar 26, 2026",
    logo: logo("notion.so"),
    category: "Productivity",
    status: "pending",
    type: "expense",
    cardLast4: "7321",
  },
  {
    id: "t17",
    userId: "1",
    merchant: "Vercel Pro",
    transactionId: "INV_776655",
    amount: -20.0,
    date: "Mar 25, 2026",
    logo: logo("vercel.com"),
    category: "Technology",
    status: "completed",
    type: "expense",
    merchantInfo: "Vercel Inc, San Francisco, CA",
    cardLast4: "4589",
  },
  {
    id: "t18",
    userId: "1",
    merchant: "LinkedIn Premium",
    transactionId: "INV_665544",
    amount: -29.99,
    date: "Mar 24, 2026",
    logo: logo("linkedin.com"),
    category: "Productivity",
    status: "completed",
    type: "expense",
    cardLast4: "9012",
  },
  {
    id: "t19",
    userId: "1",
    merchant: "Apple iCloud+",
    transactionId: "INV_554433",
    amount: -2.99,
    date: "Mar 23, 2026",
    logo: logo("apple.com"),
    category: "Technology",
    status: "completed",
    type: "expense",
    cardLast4: "4589",
  },
  {
    id: "t20",
    userId: "1",
    merchant: "Airbnb Booking",
    transactionId: "INV_443322",
    amount: -245.0,
    date: "Mar 22, 2026",
    logo: logo("airbnb.com"),
    category: "Travel",
    status: "completed",
    type: "expense",
    merchantInfo: "Airbnb Inc, San Francisco, CA",
    cardLast4: "9012",
  },
  {
    id: "t21",
    userId: "1",
    merchant: "Freelance Project",
    transactionId: "TXN_332211",
    amount: 3200.0,
    date: "Mar 21, 2026",
    logo: logo("wise.com"),
    category: "Income",
    status: "completed",
    type: "income",
    merchantInfo: "Wise (TransferWise), London, UK",
  },
  {
    id: "t22",
    userId: "1",
    merchant: "Target",
    transactionId: "INV_221100",
    amount: -67.43,
    date: "Mar 20, 2026",
    logo: logo("target.com"),
    category: "Shopping",
    status: "completed",
    type: "expense",
    cardLast4: "9012",
  },
  {
    id: "t23",
    userId: "1",
    merchant: "Shell Gas",
    transactionId: "INV_110099",
    amount: -52.3,
    date: "Mar 19, 2026",
    logo: logo("shell.com"),
    category: "Transport",
    status: "failed",
    type: "expense",
    notes: "Card declined — insufficient funds",
    cardLast4: "7321",
  },
  {
    id: "t24",
    userId: "1",
    merchant: "Delta Airlines",
    transactionId: "INV_009988",
    amount: -389.0,
    date: "Mar 18, 2026",
    logo: logo("delta.com"),
    category: "Travel",
    status: "pending",
    type: "expense",
    merchantInfo: "Delta Air Lines, Atlanta, GA",
    cardLast4: "9012",
  },
  {
    id: "t25",
    userId: "1",
    merchant: "Dividend — AAPL",
    transactionId: "TXN_889977",
    amount: 142.5,
    date: "Mar 17, 2026",
    logo: logo("apple.com"),
    category: "Income",
    status: "completed",
    type: "income",
    notes: "Q1 2026 dividend payment",
  },
]
